print('Nume Prenume    Pripa Andreea')
print('Adresa          mun.Bălți, str.Suceava 19') 
print('Telefon         +37368601001')
print('E-mail          pripaandreea@gmail.com')
print('Sexul           feminin')
print('Data nașterii   12.11.2004')
print('Naționalitate   moldoveancă')
print('Instituția de învățământ  Liceul Teoretic "Mihai Eminescu" ')
print('Limba maternă   limba română')
print('Limbi străine   engleza, rusa, germana')